spring:
  data:
    mongodb:
      username: batrick
      password: batrick
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8702
